import React from "react";
import Head from "next/head";
import GenerateLogo from "src/app/images/Screenshot 2024-06-03 at 2.19.12 AM.png";
import Image from "next/image";

const MainPage = () => {
  return (
    <>
      <Head>
        <title>Generate DevDB</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-b from-blue-900 to-blue-800 text-white text-center">
        <div className="flex items-center justify-center mb-8">
          <Image
            src={GenerateLogo}
            alt="Logo"
            width={64}
            height={64}
            className="h-16 mr-4"
          />
          <h1 className="text-5xl font-bold">
            <span>Generate</span> <span className="text-yellow-400">DevDB</span>
          </h1>
        </div>
        <div className="flex space-x-4 mb-8">
          <a
            href="/request-access"
            className="bg-yellow-400 text-black px-4 py-2 rounded hover:bg-yellow-500"
          >
            Request Access →
          </a>
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            className="bg-yellow-400 text-black px-4 py-2 rounded hover:bg-yellow-500"
          >
            View GitHub Repo →
          </a>
        </div>
        <a
          href="/sign-in"
          className="bg-yellow-400 text-black px-4 py-2 rounded hover:bg-yellow-500"
        >
          Sign In
        </a>
      </div>
    </>
  );
};

export default MainPage;
