# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  server:
    name: Format & build the main Next.js server
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/generate-routes"
      NEXTAUTH_SECRET: "placeholder"
      NEXTAUTH_URL: "http://localhost:3000"
      GITHUB_CLIENT_ID: "placeholder"
      GITHUB_CLIENT_SECRET: "placeholder"
      AWS_MASTER_USERNAME: "placeholder"
      AWS_MASTER_PASSWORD: "placeholder"
      AWS_ACCESS_KEY_ID: "placeholder"
      AWS_SECRET_ACCESS_KEY: "placeholder"
      AWS_SESSION_TOKEN: "placeholder"

    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
        working-directory: ./
      - run: bun run format
        working-directory: ./
      - run: bun test
        working-directory: ./
      - run: bun run build
        working-directory: ./
