# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  server:
    name: Format & build the main Next.js server
    runs-on: ubuntu-latest

    env:
      SKIP_ENV_VALIDATION: TRUE

    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
        working-directory: ./
      - run: bun run format
        working-directory: ./
      - run: bun test
        working-directory: ./
      - run: bun run build
        working-directory: ./
